### ISSUE TITLE
Tip (not an issue)

### ISSUE THREAD

**Issue by c33s** [r0f1/linux#1]
found you on dev.to because you liked a post of mine. headed over to your repo and took a look.

i also have a linux command list collection but pet really look very interesting (had no chance to test it but it looks really promising)

https://github.com/knqyf263/pet 

found pet on dev.to https://dev.to/brpaz/my-linux-development-environment-of-2018-ch7 the reason why i joined :)

maybe helpful for you

**Comment by r0f1** [comment]
Nice, thank you! Looks like a real useful tool! The post you linked also some nice links :)
